name = "ImageAnnotationsIO"
uuid = "a23dbe5c-0729-48bd-99f5-ede0f658dfcb"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
LightXML = "0.9"
julia = "1"
